
name: 'dbt_training_demo'
version: '1.0.0'

profile: 'dbt_training_demo'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:         
  - "target"
  - "dbt_packages"


models:
  dbt_training_demo:
    silver_airbnb:
     +schema: 'SILVER_AIRBNB'
     +materialized: view
